name: Terraform

on:
  pull_request:
    paths:
      - "infra/**"
      - "app/**"
      - ".github/workflows/terraform.yml"
  push:
    branches:
      - main
    paths:
      - "infra/**"
      - "app/**"
      - ".github/workflows/terraform.yml"

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  AWS_REGION: eu-central-1
  TF_BACKEND_CONFIG: backend/dev.hcl
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Write Terraform backend config
        run: |
          cat > "${{ env.TF_BACKEND_CONFIG }}" <<EOF
          bucket         = "${{ secrets.TF_STATE_BUCKET }}"
          key            = "serverless-task-api/dev/terraform.tfstate"
          region         = "${{ env.AWS_REGION }}"
          dynamodb_table = "${{ secrets.TF_LOCK_TABLE }}"
          encrypt        = true
          EOF

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend-config="${{ env.TF_BACKEND_CONFIG }}"

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Terraform apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
